ES5Harness.registerTest({id:"15.2.3.6-4-298",path:"TestCases/chapter15/15.2/15.2.3/15.2.3.6/15.2.3.6-4-298.js",description:"Object.defineProperty - 'O' is an Arguments object, 'name' is own accessor property of 'O', test TypeError is thrown when updating the [[Set]] attribute value of 'name' which is defined as non-configurable (10.6 [[DefineOwnProperty]] step 4)",test:function(){return function(){function b(){return 10}function c(a){this.setVerifyHelpProp=a}Object.defineProperty(arguments,"0",{get:b,
set:void 0,enumerable:!1,configurable:!1});try{Object.defineProperty(arguments,"0",{set:c})}catch(a){return a instanceof TypeError&&accessorPropertyAttributesAreCorrect(arguments,"0",b,void 0,void 0,!1,!1)}return!1}(0,1,2)},precondition:function(){return fnExists(Object.defineProperty)&&fnSupportsArrayIndexGettersOnObjects()&&fnExists(Object.getOwnPropertyDescriptor)}});
